const ARR1 = [
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
        'a',
        'b',
        'c',
        'd',
        'e',
        'f',
        'g',
        'h',
        'i',
        'j',
        'k',
        'l',
        'm',
        'n',
        'o',
        'p',
        'q',
        'r',
        's',
        't',
        'u',
        'v',
        'w',
        'x',
        'y',
        'z',
        '0',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '+',
        '/',
    ],
    ARR2 = [
        65,
        66,
        67,
        68,
        69,
        70,
        71,
        72,
        73,
        74,
        75,
        76,
        77,
        78,
        79,
        80,
        81,
        82,
        83,
        84,
        85,
        86,
        87,
        88,
        89,
        90,
        97,
        98,
        99,
        100,
        101,
        102,
        103,
        104,
        105,
        106,
        107,
        108,
        109,
        110,
        111,
        112,
        113,
        114,
        115,
        116,
        117,
        118,
        119,
        120,
        121,
        122,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        43,
        47,
    ];

const v_3kj = [], // v_3kj это полная копия ARR1
    v_4kj = [],
    v_5kj = [],
    v_6kj = [],
    v_7kj = [],
    v_8kj = [],
    v_9kj = [],
    v_akj = [];

for (let index = 0; index < 64; index++) {
    const v_bkj = ARR2[index];

    v_3kj[index] = ARR1[index];
    v_4kj[v_bkj] = index;
    v_5kj[v_bkj] = index << 2;
    v_6kj[v_bkj] = (index << 4) & 255;
    v_7kj[v_bkj] = (index << 6) & 255;
    v_8kj[v_bkj] = index >> 2;
    v_9kj[v_bkj] = index >> 4;
    v_akj[v_bkj] = true;
}

const A8f: TA8f = [v_4kj, v_5kj, v_6kj, v_7kj, v_8kj, v_9kj, v_akj];

export default A8f;
export type TA8f = [number[], number[], number[], number[], number[], number[], boolean[]];
